### ISSUE TITLE
Feature - Define Global AES encryption settings, under export policy.

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#156]
Would be nice to define Global AES encryption through net-as-code:
![image](https://github.com/user-attachments/assets/dbfa65f6-4e10-4878-9ae2-c1585174d9fc)
![image](https://github.com/user-attachments/assets/b48dd7bc-1585-4198-ad9e-ce87d71bb182)

br

**Comment by jorgenspange** [comment]
hi, @juchowan 

Wow, thanks!

Does the syntax has to be password!password! like it's in the example or could the string be whatever?

br
Jørgen

**Comment by juchowan** [comment]
no, it's just example password we used, attribute accepts a string value with max 32 characters

**Comment by jorgenspange** [comment]
Great, thanks for the assistance! My request is then answered.
