### ISSUE TITLE
JSON schema removed, other alternatives

### ISSUE THREAD

**Issue by peslung** [netascode/terraform-aci-nac-aci#171]
Have been using the [schema.json](https://github.com/netascode/nac-validate/commit/70e87184200e776265f59d53df942f2423020318) in VSCode with YAML extension for validation and coding assistance.

Working offline and pointing to the schema in each yaml-file
`# yaml-language-server: $schema=../../nac-schema/schema.json`

Schema file we have been using is not updated anymore, and removed from github and [JSON Schema Store](https://www.schemastore.org/json/)

Other alternatives for schema and NAC yaml code?

**Comment by danischm** [comment]
The schema is still in the JSON Schema Store, though the repo has changed. It is now located here: https://github.com/netascode/schema

**Comment by peslung** [comment]
Thank you!

I searched old name Nexus-as-Code, new name Network-as-Code
