### ISSUE TITLE
Autogeneration of LF/SPINE fabric/access profiles fails when suffix is added 

### ISSUE THREAD

**Issue by alexanderdeca** [netascode/terraform-aci-nac-aci#20]
For example, in the module module "aci_fabric_leaf_switch_profile_auto" (starting code line 368), the replace statement does not account for when a suffix is added in the default values for autogenerating fabric/access leaf/spine profiles, etc.

Working "LEAF\\g<id>" -> output is LEAF1001, LEAF1002 etc..
Not working "LEAF\\g<id>_SwPro" -> output is LEAF

**Comment by danischm** [comment]
Thanks for raising the issue! This has already been fixed (https://github.com/netascode/terraform-aci-nac-aci/commit/c4be586c33f570dc408118bed8b0602b4bc4e14c) and will be included in the next release.

**Comment by alexanderdeca** [comment]
Hi,

Any update on when the new release will be available ?

Thanks

Alexander

From: Daniel Schmidt ***@***.***>
Date: Monday, 2 October 2023 at 10:02
To: netascode/terraform-aci-nac-aci ***@***.***>
Cc: Alexander Deca ***@***.***>, Author ***@***.***>
Subject: Re: [netascode/terraform-aci-nac-aci] Autogeneration of LF/SPINE fabric/access profiles fails when suffix is added (Issue #20)

Closed #20<https://github.com/netascode/terraform-aci-nac-aci/issues/20> as completed.

**Comment by danischm** [comment]
We are aiming for end of October, beginning of November.

**Comment by alexanderdeca** [comment]
Hey Daniel,

Any update on the drop for the new release? 😊

thanks

From: Daniel Schmidt ***@***.***>
Date: Monday, 16 October 2023 at 10:05
To: netascode/terraform-aci-nac-aci ***@***.***>
Cc: Alexander Deca ***@***.***>, Author ***@***.***>
Subject: Re: [netascode/terraform-aci-nac-aci] Autogeneration of LF/SPINE fabric/access profiles fails when suffix is added (Issue #20)

We are aiming for end of October, beginning of November.

**Comment by danischm** [comment]
We are working towards it. It should be ready by end of this week or latest next week. If you want to test the latest enhancements, you can always source the module directly from git:
```
module "aci" {
  source = "github.com/netascode/terraform-aci-nac-aci.git?ref=main"
  
  ...
}
```

**Comment by alexanderdeca** [comment]
Thanks!

From: Daniel Schmidt ***@***.***>
Date: Tuesday, 7 November 2023 at 11:08
To: netascode/terraform-aci-nac-aci ***@***.***>
Cc: Alexander Deca ***@***.***>, Author ***@***.***>
Subject: Re: [netascode/terraform-aci-nac-aci] Autogeneration of LF/SPINE fabric/access profiles fails when suffix is added (Issue #20)

We are working towards it. It should be ready by end of this week or latest next week. If you want to test the latest enhancements, you can always source the module directly from git:

module "aci" {

  source = "github.com/netascode/terraform-aci-nac-aci.git?ref=main"



  ...

}
