### ISSUE TITLE
MGMT EPG only supports oob/inb for validation and NOT default

### ISSUE THREAD

**Issue by alexanderdeca** [netascode/terraform-aci-nac-aci#40]
Within the mgmt tenant, there is a default node mgmt epg (Out-of-Band EPG - default) , however, this value is not accepted as entry for validation for different fabric policies such as dns, tacacs etc.

However this is the default epg used by the APIC controllers and we cannot change this, resulting in mismatching node mgmt epg for leafs/spines vs apic and thus this reflects the contract that needs to be applied.

<img width="1238" alt="Screenshot 2023-11-27 at 15 20 50" src="https://github.com/netascode/terraform-aci-nac-aci/assets/16814673/3cde9aa0-489c-4b2f-ac77-67d97354072e">

It would make sense to use the default oob epg that is available under the mgmt tenant to have all leafs/spines/apic use the default oob epg.

ERROR:
======

Error: Invalid value for variable
│ 
│   on .terraform/modules/nac-aci/aci_fabric_policies.tf line 160, in module "aci_dns_policy":
│  160:   mgmt_epg_type = try(each.value.mgmt_epg, local.defaults.apic.fabric_policies.dns_policies.mgmt_epg)
│     ├────────────────
│     │ var.mgmt_epg_type is "default"
│ 
│ Allowed values are `inb` or `oob`.
│ 
│ This was checked by the validation rule at .terraform/modules/nac-aci/modules/terraform-aci-dns-policy/variables.tf:16,3-13.

**Comment by danischm** [comment]
What you configure under the dns policy is only the type of EPG you want to refer to, which is either `inb` or `oob`. The actual EPG name is specified under `node_policies` which by default is set to `default` (see https://github.com/netascode/terraform-aci-nac-aci/blob/53585f87dc536155a6e083e5ef913f0d94b1a75a/defaults/defaults.yaml#L648).

**Comment by alexanderdeca** [comment]
Hi Daniel,

Thanks for the feedback, you can close this case.

Best regards

Alexander

From: Daniel Schmidt ***@***.***>
Date: Wednesday, 13 December 2023 at 15:32
To: netascode/terraform-aci-nac-aci ***@***.***>
Cc: Alexander Deca ***@***.***>, Author ***@***.***>
Subject: Re: [netascode/terraform-aci-nac-aci] MGMT EPG only supports oob/inb for validation and NOT default (Issue #40)

What you configure under the dns policy is only the type of EPG you want to refer to, which is either inb or oob. The actual EPG name is specified under node_policies which by default is set to default (see https://github.com/netascode/terraform-aci-nac-aci/blob/53585f87dc536155a6e083e5ef913f0d94b1a75a/defaults/defaults.yaml#L648).
