### ISSUE TITLE
Apply service graph template uncertainty.

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#44]
Good day,

After you have created a service graph template in ACI you have to right click it to and click apply. This apply option does not seem to be available from the module. 

Is it anything that I dont know, or is this not implemented per now?

Best regards

**Comment by danischm** [comment]
The "right-click apply" is essentially a wizard to create a device selection policy. See: https://developer.cisco.com/docs/nexus-as-code/#!device-selection-policy

**Comment by jorgenspange** [comment]
Perfect! Thank you so much for the prompt response😄
