### ISSUE TITLE
OOB Node Adress - Management EPG

### ISSUE THREAD

**Issue by jorgenspange** [netascode/terraform-aci-nac-aci#72]
Link: https://developer.cisco.com/docs/nexus-as-code/#!oob-node-address/oob-node-address

Is there any option to add OOB Management EPG when assigning oob-node-address, as there is in the GUI:

<img width="631" alt="image" src="https://github.com/netascode/terraform-aci-nac-aci/assets/75736500/3cf66791-62cd-4c22-882d-56a5e5f10e70">

Br

**Comment by juchowan** [comment]
Under node_policies you can specify oob_endpoint_group which is the name of OOB EPG that will be used for all nodes

**Comment by jorgenspange** [comment]
@juchowan That's correct. Should I define my apics in the node_policies aswell? Because the apics are assigned to default epg, and have to be added to oob epg.

**Comment by juchowan** [comment]
yes, you can define APICs there as well and assign them to oob epg

**Comment by danischm** [comment]
Does that answer your question?

**Comment by danischm** [comment]
Will close this for now, if there are further questions feel free to reopen this issue.
