### ISSUE TITLE
Question: add filter in tenant common to a contract's subject on other tenant

### ISSUE THREAD

**Issue by micronemo** [netascode/terraform-aci-nac-aci#85]
how can i add a filter present in the tenant common to subject of a contract in a client tenant ?

**Comment by danischm** [comment]
Filters are referenced by its name, so simply use the filter's name and if it is not existing within the subject's tenant, ACI will try to resolve it via the common tenant.

**Comment by danischm** [comment]
Did this answer your question?

**Comment by micronemo** [comment]
yes works
