### ISSUE TITLE
question: How can I create a routed domain without associating it with a vlan pool

### ISSUE THREAD

**Issue by micronemo** [netascode/terraform-aci-nac-aci#87]
How can I create a routed domain without associating it with a vlan pool which is a mandatory field 

---
apic:
  access_policies:
    routed_domains:
       - name: L3Out
         vlan_pool: ??? <- mandatory
         
Leave the VLAN pool field blank because you do not need it for routed interface L3
For example, you need the pool for L3 connections with SVIs and subinterfaces.

**Comment by danischm** [comment]
We are adding this functionality in the next release.
